.circleci/config.yml
Dockerfile
README.md
bin/setup
docker-compose.yml
package.json
src/Panel/Panel.component.tsx
tslint.json

Add support for Docker and CI

---

.circleci/config.yml
Dockerfile
bin/release
package-lock.json
package.json

Add deployment to gh-pages

---

package-lock.json
package.json
src/Table/Table.component.tsx
src/themes/default.ts

@Dantiff 
Table component was missing some theme properties and was prevented from opening.

adds missing theme properties for table

---

src/RadioButton/RadioButton.component.tsx

@ben-dalton @Dantiff 
[TPMTI-61](https://technekes.atlassian.net/browse/TPMTI-61)
Apart from improving the look of the component to make the disabled state distinctive the component has all the other items checked

Add disabled styles to label

---

src/Tabs/Tab.component.tsx
src/Tabs/TabList.component.tsx
src/Tabs/TabPanel.component.tsx
src/Tabs/Tabs.component.tsx
src/themes/default.ts

[TPMTI-39](https://technekes.atlassian.net/browse/TPMTI-39)

Update tab styling

---

src/RadioButton/RadioButton.component.tsx
src/RadioButton/RadioButton.stories.tsx
src/RadioButtonGroup/RadioButtonGroup.stories.tsx

[TPMTI-69](https://technekes.atlassian.net/browse/TPMTI-69)
Remove rbStyle from Radio Button

Remove rbStyle on Radio Button

---

src/Checkbox/Checkbox.component.tsx
src/Checkbox/Checkbox.stories.tsx

[TPMTI-63](https://technekes.atlassian.net/browse/TPMTI-63)
- Fix type error warning

Swap root tags

---

README.md
package-lock.json
package.json

release 0.1.9

---

package-lock.json
package.json
src/Toggle/Toggle.component.tsx
src/Toggle/Toggle.stories.tsx
src/Toggle/index.ts
src/index.ts
src/themes/default.ts

[TPMTI-65](https://technekes.atlassian.net/browse/TPMTI-65)
Adds toggle component

adds toggle component

---

package-lock.json
package.json
src/Table/Table.stories.tsx

update npm version

---

.gitignore
.storybook/webpack.config.js
package-lock.json
src/Modal/Modal.component.tsx
src/Modal/Modal.stories.tsx
src/Popover/Popover.component.tsx
src/themes/default.ts

[TPMTI-96](https://technekes.atlassian.net/browse/TPMTI-96)
@Dantiff @bankai254 @hamholla

Update Modal styles and options

---

src/Card/Card.component.tsx
src/Card/Card.stories.tsx
src/Card/index.ts
src/index.ts
src/themes/default.ts

@ben-dalton @Dantiff 
[TPMTI-97](https://technekes.atlassian.net/browse/TPMTI-97)

Add Card Component

---

src/Card/Card.component.tsx

Fix cardStyle typo

---

package.json
src/Modal/Modal.component.tsx

@Dantiff 
Using your change to the modal component import to resolve the styled components issue.

changes react-modal import to use default

---

.storybook/addons.js
.storybook/config.js
package-lock.json
package.json
src/themes/cobalt.ts
src/themes/default.ts

This adds the `storybook-addon-styled-component-theme` addon, which allows us to toggle the available themes in a storybook panel for each component.

adds ability to toggle themes on component

---

package-lock.json
src/Popover/Popover.component.tsx
src/Popover/Popover.stories.tsx
src/Tooltip/Tooltip.component.tsx
src/Tooltip/Tooltip.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts

Allow popover to pass arrow prop down to tippyjs

allow popover to pass arrow prop down to tippyjs

---

src/Table/Table.stories.tsx

[TPMTI-109](https://technekes.atlassian.net/browse/TPMTI-109)
@ben-dalton @Dantiff @hamholla @dorokhovich-mikhail @tdakhla

Add note on the behaviour of forcePage on pagination

---

package-lock.json
package.json
src/Table/Table.component.tsx
tsconfig.json

Typescript compiler was exporting the columns prop on Table to a `never` type, which prevented use. 
@tdakhla

fix never type added to columns in table component

---

src/Checkbox/Checkbox.component.tsx
src/Checkbox/Checkbox.stories.tsx

Adds indeterminate checkbox state and checkable knobs

Add indeterminate state for checkbox

---

src/Alert/Alert.component.tsx

matches alert border with background to remove white border on dark backgrounds.

Match border to alertbackground for dark backgroungs

---

package-lock.json
src/Popover/Popover.component.tsx
src/Popover/Popover.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts

This adds a pseudo-element with two borders to connect the border around the arrow on a popover.

adds border to popover arrow

---

src/TablePagination/TablePagination.component.tsx

[TPMTI-105](https://technekes.atlassian.net/browse/TPMTI-105)
@ben-dalton @tdakhla @hamholla 
Since the component is wrapped by a `HTML Div` element and not a package the update is minimal.

Change Props from type to interface and extend native HTML Div Element

---

src/Panel/Panel.stories.tsx

@ben-dalton 
fixes error for default styles

Remove default style from panel

---

src/Checkbox/Checkbox.component.tsx
src/themes/cobalt.ts
src/themes/default.ts

Adds new checkbox styling to match mock ups

Add solid checkbox when selected

---

src/IconButton/IconButton.component.tsx
src/Input/Input.component.tsx
src/Input/Input.stories.tsx

Allows the Input component to accept and position an Element, Component or string to the left or right.
[CCIBI-62](https://technekes.atlassian.net/browse/CCIBI-62)

Add Icon and Icon positioning capabilities to Input component

---

src/Collapse/Collapse.component.tsx
src/Collapse/Collapse.stories.tsx
src/Collapse/collapse.css
src/Collapse/index.ts
src/Panel/Panel.component.tsx
src/Panel/Panel.stories.tsx
src/Panel/PanelBody.component.tsx
src/Panel/PanelHeader.component.tsx
src/Panel/index.ts
src/index.ts

- Adds a Collapse component
- Reworks the Panel component
- Demonstrates the use of the Collapse component with the Panel component
[TPMTI-103](https://technekes.atlassian.net/browse/TPMTI-103)

Add Collapse component and extract Panel components

---

src/Input/Input.component.tsx
src/Input/Input.stories.tsx

Allows the Input component to accept and position a string or character set such as the dollar sign or percentage sign to the left or right.
[CCIBI-63](https://technekes.atlassian.net/browse/CCIBI-63)

Add addonText and addonTextPosition props and functionality to Input component

---

package-lock.json
package.json
rollup.config.prod.js
src/DatePicker/DatePicker.component.tsx
src/DatePicker/DatePicker.stories.tsx
src/index.ts

@Dantiff 
Needed to add named export config for cjs conversion with react-dates

Fix react-dates cjs build error

---

package-lock.json
package.json
src/Tabnav/Tabnav.component.tsx
src/Tabnav/Tabnav.stories.tsx
src/themes/cobalt.ts

adjusts styles for tabnav

---

package.json
src/DatePicker/DatePicker.component.tsx
src/InputGroup/InputGroup.component.tsx
src/InputGroup/InputGroup.stories.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx

Adds some missing props, like `isMulti`.

add missing react-select props

---

src/Checkbox/Checkbox.component.tsx
src/Checkbox/Checkbox.stories.tsx

[TPMTI-121](https://technekes.atlassian.net/browse/TPMTI-121)

fix onChange for checkbox component

---

src/Draggable/DraggableInfo.component.tsx
src/Typography/BodyText/BodyText.component.tsx
src/Typography/BodyText/BodyText.stories.tsx
src/Typography/Caption/Caption.component.tsx
src/Typography/Caption/Caption.stories.tsx
src/Typography/Display/Display.component.tsx
src/Typography/Display/Display.stories.tsx
src/Typography/Header/Header.component.tsx
src/Typography/Header/Header.stories.tsx
src/Typography/Title/Title.component.tsx
src/Typography/Title/Title.stories.tsx

Change sizes to numbers

---

.storybook/config.js
package-lock.json
package.json
src/DatePicker/DatePicker.component.tsx
src/DatePicker/DatePicker.stories.tsx

react-dates requires some global initialization and should be set up at the parent level.

moves react-dates to a peer dependency

---

package-lock.json
package.json
src/Card/Card.component.tsx

Makes cards full width and adjusts their box-sizing.
updates dev dependencies for react-dates

Update card styling, update react dates dependencies

---

src/Input/Input.component.tsx
src/Table/Table.component.tsx
src/Textarea/Textarea.component.tsx

Sets width to 100% and box sizing to border box for input, textarea, and table components

adjust width and border box for effected inputs

---

package-lock.json
src/Input/Input.component.tsx

Eliminate wrapping of icon on Input
@hamholla @tdakhla

add nowrap

---

CHANGELOG.md
package-lock.json
package.json

Release 0.3.8

---

src/Typography/Caption/Caption.component.tsx
src/Typography/Display/Display.component.tsx
src/Typography/Header/Header.component.tsx
src/Typography/Title/Title.component.tsx
src/themes/cobalt.ts
src/themes/default.ts

This should set font family values for cast components so they render correctly in parent application. Also allows for further customization of typography elements.

Adjust font family settings for cast

---

src/Select/Select.component.tsx
src/themes/cobalt.ts

Adjusts cast components used on dashboard to fit mockups.

adjust dashboard component styles

---

package-lock.json
package.json

release 0.4.1

---

package-lock.json
src/themes/cobalt.ts

fixes header size 20 to match mockups

adjusts header font size to match mockups

---

.circleci/config.yml

[CCIBI-82](https://technekes.atlassian.net/browse/CCIBI-82)
This PR updates circleci to only run a build and deploy for release branches while linting all branches

Automate Deployment for Release Branch Only [CCIBI-82]

---

package-lock.json
src/Tabnav/Tabnav.component.tsx
src/Tabnav/Tabnav.stories.tsx

Account for disabled nav items in cast, add styling for disabled dropdown items

Disabled Tabnav items

---

src/Colors/Colors.stories.tsx
src/DatePicker/DatePicker.component.tsx
src/DatePickerRange/DatePickerRange.component.tsx
src/Modal/Modal.stories.tsx
src/Pagination/Pagination.component.tsx

[CCIBI-269](git push --set-upstream origin feature/CCIBI-269/proptypes-fixes)

fixes with proptypes and common warnings of types

---

CHANGELOG.md
package.json

Release 0.4.3

---

src/Panel/Panel.component.tsx
src/Panel/PanelBody.component.tsx
src/Panel/PanelHeader.component.tsx
src/Select/Select.component.tsx
src/themes/cobalt.ts

Minor styling adjustments to match Niels' design.

adjust cast styling to match mockups

---

.circleci/config.yml
CHANGELOG.md
package-lock.json
package.json
src/Colors/Colors.stories.tsx
src/DatePicker/DatePicker.component.tsx
src/DatePickerRange/DatePickerRange.component.tsx
src/Modal/Modal.stories.tsx
src/Pagination/Pagination.component.tsx

Feature/release 0.4.3

---

package-lock.json
src/Panel/PanelHeader.component.tsx

adjusts panel header border colors

adjust panel border settings

---

src/Table/Table.component.tsx
src/Table/Table.stories.tsx

adds table alignment styling. Accounts for sorting arrows

adds table alignment styling

---

CHANGELOG.md
package.json

update changelog, bump version number

update changelog, version

---

src/Checkbox/Checkbox.component.tsx

fixes "hidden feature" checkbox

position relative checkbox label

---

src/Select/Select.component.tsx

multiple style tweaks to cast select

Select updates

---

src/DatePicker/DatePicker.component.tsx
src/DatePickerRange/DatePickerRange.component.tsx

Updates Datepicker icon padding, border color

Datepicker styling

---

src/Typography/Link/Link.component.tsx
src/Typography/Link/Link.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts

@ben-dalton 
adds disabled prop to cast link component

add disabled prop to link component

---

CHANGELOG.md
package.json

Bump version to 0.4.5, update changelog

bump version to 0.4.5 and update changelog

---

package.json
src/Select/Select.component.tsx

Release 0.4.6

---

package-lock.json
src/Select/Select.component.tsx

adds menu target to cast select. Attempts to set font family for dropdown in component itself.

add select menu target to select

---

src/DatePickerRange/DatePickerRange.component.tsx

fixes theme provider for datepicker range

fixes themeprovider for datepicker range

---

src/Modal/Modal.component.tsx
src/themes/cobalt.ts
src/themes/default.ts

Adds margin top to modal to prevent it from sliding beneath navbar.

Add margin top to modal

---

package-lock.json
package.json
src/DatePickerRange/DatePickerRange.component.tsx
src/Modal/Modal.component.tsx
src/Select/Select.component.tsx
src/themes/cobalt.ts
src/themes/default.ts

Release 0.4.7

---

CHANGELOG.md
package.json

bump version 0.4.8

---

.circleci/config.yml
package-lock.json
package.json
src/Modal/Modal.component.tsx
src/Select/Select.component.tsx
src/themes/cobalt.ts
src/themes/default.ts

Release 0.4.8

---

CHANGELOG.md
package.json

bump version 0.4.9

---

.circleci/config.yml
CHANGELOG.md
package.json

Release 0.4.9

---

package-lock.json
package.json
src/Table/Table.component.tsx

styles empty state for react-table

Style placeholder state

---

package-lock.json
package.json
src/Table/Table.component.tsx

Release 0.4.10

---

src/Table/Table.component.tsx

@tdakhla 
reverts no rows styling in table componenet

reverts no rows styling

---

package-lock.json
package.json
src/Table/Table.component.tsx

Release 0.4.11

---

package.json

Release 0.4.12

---

src/Table/Table.component.tsx

Revert "reverts no rows styling"

---

.gitignore
package-lock.json
package.json
src/Collapse/Collapse.component.tsx
src/Collapse/Collapse.stories.tsx
src/Input/Input.component.tsx
src/Panel/Panel.stories.tsx
src/Panel/PanelHeader.component.tsx
src/Select/Select.component.tsx
src/Table/Table.component.tsx
src/Table/Table.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts

Release 0.4.14

---

package.json
src/Table/Table.component.tsx

Release 0.4.15

---

src/Table/Table.component.tsx
src/Table/Table.stories.tsx

@tdakhla @ben-dalton 
Updates table expander icon, reorganizes defaultTable props

adjust table arrows, reorder default props

---

src/Table/Table.component.tsx
src/Table/Table.stories.tsx

Set width for input wrapper, add sample inputs to storybook

CCIBI-319 Input Fields To Large in IE11

---

package-lock.json
src/ListGroup/ListGroup.component.tsx

@tdakhla 
Corrects List group icon direction.

Adjust icon direction for collapse on listgroup

---

package.json
src/Select/Select.component.tsx
src/Select/Select.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts

Release 0.4.17

---

src/Table/Table.component.tsx

Fix right-alignment for flex elements

CCIBI-354 Some Product Overview table values are not aligned at right

---

package-lock.json
src/ListGroup/ListGroup.component.tsx

Adds active state to open list group

Adds highlight to active listgroup

---

src/Modal/Modal.component.tsx

…the Average List Price Modal, Buttons are off page as modal does not resize in IE (IE11 Only)
Setup fixed height for IE11

Sets fixed height on Modal for IE11 CCIBI-362

---

package-lock.json
package.json
src/Checkbox/Checkbox.component.tsx
src/ListGroup/ListGroup.component.tsx
src/Modal/Modal.component.tsx
src/Panel/PanelHeader.component.tsx
src/RadioButton/RadioButton.component.tsx
src/Table/Table.component.tsx

Release 0.4.18

---

package.json
src/Table/Table.component.tsx
src/Table/Table.stories.tsx
src/Tooltip/Tooltip.component.tsx

Release 0.4.19

---

package-lock.json
package.json
src/Table/Table.component.tsx
src/TablePagination/TablePagination.component.tsx
src/TablePagination/TablePagination.stories.tsx

Release 0.4.20

---

package.json

update to version 0.4.22

---

package.json

Update version to 0.4.24

---

package.json
src/RadioButton/RadioButton.component.tsx
src/Table/Table.component.tsx
src/themes/verdant.ts

updates table header padding, border settings and removes console log in radio button.

update verdant table headers

---

package.json
src/RadioButton/RadioButton.component.tsx
src/Table/Table.component.tsx
src/themes/verdant.ts

Release 0.4.25

---

src/InputGroup/InputGroup.component.tsx
src/InputGroup/InputGroup.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Replace InputGroup vertical options with horizontal, extend styles to support horizontal InputGroups

CCIBI-1059 Cast UI: Horizontal label for Input Group

---

package-lock.json
package.json
src/Collapse/Collapse.component.tsx
src/Collapse/Collapse.stories.tsx
src/InputGroup/InputGroup.component.tsx
src/InputGroup/InputGroup.stories.tsx
src/Pagination/Pagination.component.tsx
src/Panel/Panel.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Release 0.4.31

---

.circleci/config.yml

Adds the ability to create a beta version of the package from the `env/qa` branch. Taken from work by @mgeitz in `ui-modules`.

adds beta deployments

---

package.json
src/Sidenav/SideNavbar.component.tsx

Using higher-order components theme provided by ThemeProvider instead of hardcoded theme

CCIBI-1120

---

package-lock.json
package.json
src/Sidenav/SideNavbar.component.tsx

Release 0.4.33

---

package-lock.json
package.json
src/Pagination/Pagination.component.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx

Release 0.4.34

---

src/DatePickerRange/DatePickerRange.component.tsx

[CCIBI-1236](https://technekes.atlassian.net/browse/CCIBI-1236)

Add optional readOnly prop to Date Picker Range

---

src/FileUpload/FileUpload.component.tsx

Prevent onDragEnter (IE11 issue)

CCIBI-1095 Drag and Drop is not working for attachment

---

package.json
src/FileUpload/FileUpload.component.tsx
src/Pagination/Pagination.component.tsx

Release 0.4.36

---

src/Panel/Panel.stories.tsx
src/Panel/PanelHeader.component.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Collapsible Panel must be displayed as aggregated table row

Collapsible Panel: add iconPosition parameter, edit styles

---

src/FileUpload/FileUpload.component.tsx

Clear input after file selecting

CCIBI-1227 Nothing happens if attach same set of files

---

package.json

@ben-dalton 
move plex to devdependencies
update version

Move plex to devdependencies

---

package-lock.json
package.json
src/Checkbox/Checkbox.component.tsx
src/Checkbox/Checkbox.stories.tsx

Release 2019-11-26

---

src/Tabs/Tab.component.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Extract tab style to theme configuration
Custom styles for cobalt theme

CCIBI-2023 UX: Tab styles

---

CHANGELOG.md
src/Button/SButton.ts
src/themes/cobalt.ts

@ben-dalton 
Updates min width for buttons
Updates padding for buttons

Change min width and padding for buttons

---

src/ListGroup/ListGroup.component.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

CCIBI-2043 UX - Planned Activities Chevron size & rotation

---

CHANGELOG.md
package.json

Update version for release

---

src/themes/cobalt.ts

setup table border for cobalt theme only

CCIBI-2052 Add Table Border

---

src/Checkbox/Checkbox.component.tsx
src/Input/Input.component.tsx
src/themes/cobalt.ts

adjust checkbox alignment
reduce input with add-on padding
addresses issues found in - https://technekes.atlassian.net/browse/CCIBI-2142

CCIBI-2142: Adjust input with addon padding, checkbox alignment

---

src/Input/Input.component.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Setup height for inputs with/without icons - always use wrapper border

CCIBI-2130 Search Box Text is not Vertically Aligned

---

CHANGELOG.md
package-lock.json
package.json

Update version to 1.5.2 number and changelog

Update version to 1.5.2 number and changelog

---

src/Select/Select.component.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

centers text inside select inputs.

Vertically center select inputs

---

CHANGELOG.md
package.json

Update version number and changelog 1.5.3

Update version number and changelog 1.5.3

---

src/Input/Input.component.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

[CCIBI-2035](https://technekes.atlassian.net/browse/CCIBI-2035)
Adjusts focus to wrap entire input by moving span into input and positioning absolute. Accounts for input sizes across all themes.

Update input with addon/icon focus state [CCIBI-2035]

---

src/Spinner/Spinner.component.tsx

[CCIBI-2488](https://technekes.atlassian.net/browse/CCIBI-2488)
Remove default borderColor prop that was overwriting styles.

Spinner updates [CCIBI-2488]

---

src/Tabs/Tab.component.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

[CCIBI-2487](https://technekes.atlassian.net/browse/CCIBI-2487)
Add borderColor option for themes, change tab color to drk800

Update tab colors [CCIBI-2487]

---

src/Button/SButton.ts
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Setup button sizes according to grid values (28/32/40 - sm/md/lg)

CCIBI-2526 Cast UI Button styles

---

CHANGELOG.md
package.json

Update changelog, version number 1.5.4

Update changelog, version number 1.5.4

---

CHANGELOG.md
package.json

Update version prepare for release 1.5.5

Update version prepare for release 1.5.5

---

CHANGELOG.md
package.json
src/Checkbox/Checkbox.component.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Release 1.5.5

---

CHANGELOG.md

update changelog for 1.5.7

---

CHANGELOG.md
package-lock.json
package.json
src/themes/cobalt.ts

****updates gilroy font for Cobalt to semibold

Feature/update changelog 1.5.8

---

src/Pagination/Pagination.component.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx
src/Table/Table.component.tsx
src/themes/cobalt.ts

Updates pagination select id & select control id placement.
Also updates styling for pagination controls to match wireframes

update select control ids

---

CHANGELOG.md
package-lock.json
package.json

update version & changelog
- [#652](https://github.com/technekes/cast-ui/pull/652): updates select styling & pagination styling for tables. - [@hamholla](https://github.com/hamholla)

update version & changelog

---

src/Pagination/Pagination.component.tsx
src/Pagination/Pagination.stories.tsx

CCIBI-2950 CAST UI: Pagination component doesn't respect pageSize

---

src/Select/Select.component.tsx
src/Select/Select.stories.tsx

CCIBI-2951 Select component doesn't respect provided values

---

CHANGELOG.md
package.json
src/Pagination/Pagination.component.tsx
src/Pagination/Pagination.stories.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx

Production Release 1.5.10

---

CHANGELOG.md
package-lock.json
package.json
src/Checkbox/Checkbox.component.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx

Production Release 1.5.11

---

src/utils/static/fonts.css

removes css from fonts.css file

remove non used css

---

CHANGELOG.md
package.json

Update changelog, version number

prep for 1.5.17

---

CHANGELOG.md
package.json
src/Button/SButton.ts
src/Modal/Modal.component.tsx
src/themes/azure.ts
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts
src/utils/static/fonts.css

Release 1.5.17

---

src/DatePickerRange/DatePickerRange.component.tsx
src/themes/cobalt.ts

Fix select size, fix date picker border color

CCIBI-2613 Input alignment

---

src/themes/azure.ts
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

sets dropdown indicator color to drk800 instead of primary for all themes

Adjust color for dropdown indicator colors

---

src/Select/Select.component.tsx

move error styling for selects into cast

Handle error styling for select

---

src/Select/Select.component.tsx
src/themes/azure.ts
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

remove primary styles from input group

Remove primary styling from input group

---

package.json
src/DatePicker/DatePicker.component.tsx
src/DatePicker/DatePicker.stories.tsx
src/DatePicker/DatePickerStyles.css

Adds styles to react-dates while using the withPortal prop.

Add styles to React-Dates while using WithPortal

---

CHANGELOG.md
package.json
src/DatePicker/DatePicker.component.tsx
src/DatePicker/DatePicker.stories.tsx

Move datepicker style import from story to component 
update changelog

Move datepicker style import from story to component 

---

src/Select/Select.component.tsx
src/Select/Select.stories.tsx

CCIBI-3528 Dropdown - clear selection style

---

CHANGELOG.md
package.json

Updating version and changelog

---

src/Input/Input.component.tsx
src/Input/Input.stories.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx

Revert "CCIBI-3739: Input component improvements"

---

src/Select/Select.component.tsx
src/Select/Select.stories.tsx
src/themes/azure.ts
src/themes/cobalt.ts
src/themes/default.ts
src/themes/verdant.ts
src/themes/windfall.ts

Fix styles for non-searchable Select
Do not override provided classes

CCIBI-3979 Use common Select components on Claims/Competitives forms

---

src/themes/azure.ts
src/themes/cobalt.ts
src/themes/default.ts
src/themes/umber.ts
src/themes/verdant.ts
src/themes/windfall.ts

Increase badge side padding on all themes

Increase badge side padding on all themes

---

CHANGELOG.md
package-lock.json
src/Input/Input.component.tsx

Fix input styles to make input text visible

CCIBI-5429 Input text is invisible if selected using autofill

---

package-lock.json
src/Button/SButton.ts

Button ouline, the border is set to be darker on hover

style(button): button outline border set to darker shade on hover

---

src/Input/Input.component.tsx

when typing on input field the new line cursor jumps to the end when typing eg typing "123" infront
of "hello" leads to "1hello23"
CCIBI-5695

fix(input): typing on input jumps to last character fix

---

src/Button/SButton.ts

Fixed shadows for buttons and border outline in the Button component

fix(button): fixed shadows and border outline in Button

---

src/themes/falu.ts

Adds Falu theme to Cast and addresses border radius on input

feat(adds a theme): adds Falu theme to Cast

---

src/Table/Table.component.tsx

updated table styling to support justify-content-center using the class name center-align
CCIBI-4866

style(table): updated table styling to support justify-content-center

---

src/Tabs/Tab.component.tsx

fixes slanted borders on tabs component

fix(component): tabs border fix

---

src/Input/Input.component.tsx

Removes the margin on button in an input

fix(input.component): removes margin on button

---

src/Select/SelectCheckbox.component.tsx

previous menu for select with checkbox had no max height and was bad ux for longer menu options
CCIBI-4877

fix(select checkbox): fixed maximum menu height for select with checkbox

---

src/Panel/PanelHeader.component.tsx

Change direction of panel header chevron when using collapse

fix(panelheader): rotate panel header chevron

---

src/Select/Select.component.tsx
src/Select/Select.stories.tsx
src/Select/SelectCheckbox.component.tsx

Adds corresponding ids to options in Select Componenet to support automated QA testing

feat(select component): adds ids to options in Select

---

src/Select/Select.component.tsx
src/Select/Select.stories.tsx

feat(select): update select

---

src/Button/Button.component.tsx
src/RadioButton/RadioButton.component.tsx
src/Textarea/Textarea.component.tsx

update ids for radiobutton, button, and textarea

feat: update ids for components

---

src/Button/Button.stories.tsx
src/Select/Select.component.tsx
src/Select/SelectCheckbox.component.tsx
src/Textarea/Textarea.stories.tsx
src/Typography/Link/Link.component.tsx

updates ids on selects and links

feat: adds and updates ids for components

---

src/themes/falu.ts

adds border to falu tables in theme

fix(falu theme): add border for falu table

---

src/themes/falu.ts

updates falu theme file to get release to kickoff
BREAKING CHANGE: i need a release

feat(falu theme): falu theme update to get new release

---

src/RadioButton/RadioButton.component.tsx

show not allowed cursor on radio button before element when disabled

fix(radio component): add cursor styling to disabled radio component

---

src/RadioButton/RadioButton.component.tsx

removes radioButton from id on radiobutton group to fix issues with onchange

fix(radio button): radio button group fix

---

src/RadioButtonGroup/RadioButtonGroup.component.tsx

feat(radio button group): kick off release for fix

---

src/RadioButton/RadioButton.component.tsx

removes radioButton from id on radiobutton group to fix issues with onchange

Release 06/29/21

---

src/Sidenav/SideNavItem.component.tsx

disables side nav tooltip when side nav item is active

fix(sidenavitem): disables side nav tooltip when item is active

---

src/Select/Select.component.tsx
src/Select/SelectCheckbox.component.tsx

Making FormatGroupLabel available for all select types

---

src/Select/Select.component.tsx
src/Select/SelectCheckbox.component.tsx
src/themes/default.ts

- Making FormatGroupLabel available for all select types not just checkbox

Making FormatGroupLabel available for all select types 

---

src/Input/Input.component.tsx
src/Input/Input.stories.tsx
src/Select/Select.component.tsx
src/Select/Select.stories.tsx

BREAKING CHANGE: removes highlightFilled from Input and Select

fix(input-select): remove highlighting
