README.md
package.json

To be coupled with renaming this repo to `cast-ui`. Please also remove "Code name: Skull" from the repo description.
@johnallen3d @mgeitz

renames repo in documentation to cast-ui

---

.storybook/config.js

Storybook source was showing the wrapping hoc from the themes addon in the "Story Source". Removing some of the unused config also removes that extra wrapper.

removes unnecessary config from storybook

---

src/Select/Select.component.tsx
src/Select/Select.stories.tsx

Addresses 
- `selectedOption` type on issue #223 
- `borderRadius` restriction on issue #230 
@ben-dalton 
The `onChange` function for the `Select` component is under the `controlSpecificProps` props

Restrict border radius changes to select input

---

src/Select/Select.component.tsx

aligns multiselect indicators to prevent them from center aligning when multiple items are selected

aligns multiselect indicators

---

src/Select/Select.component.tsx

Removing these definitions for now. We need to be able to pass any of the `react-select` props to the underlying component.

Allow any react-select props to pass down

---

.circleci/config.yml

- All branches are built, build assets cached to avoid a rebuild
when deploying `env/production`

Build All Branches

---

.circleci/config.yml

- Caching the project root folder does not appear to capture build
assets required for npm pack

Correct CI Builds

---

src/Table/Table.component.tsx

Props added directly were being overridden by React Tables default props so they have been moved to `defaultProps` for the component to avoid that while maintaining flexibility

Move static Table props to defaultProps

---

src/DatePickerRange/DatePickerRange.component.tsx

Do not provide disabled attr to wrapping div element

CCIBI-321 IE11: Datepicker don't opening if one of the dates is disabled

---

src/Table/Table.component.tsx
src/TablePagination/TablePagination.component.tsx
src/TablePagination/TablePagination.stories.tsx

[CCIBI-369](https://technekes.atlassian.net/browse/CCIBI-369)
This adds the **results per page** or **page size options** drop down option and can be activated with the `showPageSizeOptions` boolean prop similar to the way `react-table` does it.
@ben-dalton @tdakhla

CCIBI-369 - Add page size options to TablePagination component

---

src/Select/Select.component.tsx

[CCIBI-369](https://technekes.atlassian.net/browse/CCIBI-369)
- fixes the issue of the `Select` drop menu not being visible on modals

Add high value z-index to menu

---

src/Typography/Link/Link.component.tsx

Added css rule
`outline: none` for the link
This will solve issue in the EDGE (for the clicked link)

added outline for the link (EDGE Issue)

---

src/Table/Table.component.tsx

remove top padding on no data component to hide header bar.
[CCIBI-2490](https://technekes.atlassian.net/browse/CCIBI-2490)

Table no data component styling [CCIBI-2490]

---

src/themes/cobalt.ts

Swap fonts to Roboto for Cobalt theme (except headers)

Swap fonts to Roboto for Cobalt theme (except headers)

---

CHANGELOG.md
package.json
src/Modal/Modal.component.tsx

- Change the default `overflow` to *visible* for the `ModalBody` for the `Modal` component to allow components that have floating menus to show the menus outside the Modal e.g. `Select` and `DatePicker`

Change overflow value to visible as default in ModalBody

---

CHANGELOG.md
package.json
src/Modal/Modal.component.tsx

- [681](https://github.com/technekes/cast-ui/pull/681): Change overflow value to visible as default in ModalBody
- [680](https://github.com/technekes/cast-ui/pull/680): Remove non used css from font.css

Release 1.5.15 (2020-04-22)

---

CHANGELOG.md
package.json
src/Modal/Modal.component.tsx

PR #681 Introduced a change to the `overflow` value of the *ModalBody* which have presented issues that require going back to the drawing board.
This is reverting that.

Revert the change made to the Modal Body overflow

---

CHANGELOG.md
package.json
src/Modal/Modal.component.tsx

- [684](https://github.com/technekes/cast-ui/pull/684): Revert the change made to the Modal Body overflow -
[@bankai254](https://github.com/bankai254)

Release 1.5.16 (2020-04-23)

---

CHANGELOG.md
package.json

- [695](https://github.com/technekes/cast-ui/pull/695): Remove primary styling from input group -
[@hamholla](https://github.com/hamholla)
- [694](https://github.com/technekes/cast-ui/pull/694): Handle error styling for select -
[@hamholla](https://github.com/hamholla)
- [691](https://github.com/technekes/cast-ui/pull/691): Adjust color for dropdown indicator colors -
[@andrey-liventsev-ontarget](https://github.com/andrey-liventsev-ontarget)

Update changelog, version number for 1.5.18

---

CHANGELOG.md
package.json
src/DatePicker/DatePicker.component.tsx
src/DatePicker/DatePicker.stories.tsx

- [700](https://github.com/technekes/cast-ui/pull/700): Move styles for datepicker to component -
[@hamholla](https://github.com/hamholla)

Release 1.5.19

---

CHANGELOG.md
package.json

- [740](https://github.com/technekes/cast-ui/pull/740): Increase badge side padding on all themes - [@hamholla](https://github.com/hamholla)
- [739](https://github.com/technekes/cast-ui/pull/739): Add Umber Theme to Cast - [@hamholla](https://github.com/hamholla)
- [723](https://github.com/technekes/cast-ui/pull/723): Use common Select components on Claims/Competitives forms - [@andrey-liventsev-ontarget](https://github.com/andrey-liventsev-ontarget)
- [722](https://github.com/technekes/cast-ui/pull/722): 3739 - [@andrey-liventsev-ontarget](https://github.com/andrey-liventsev-ontarget)

Update version, changelog for release

---

src/themes/cobalt.ts
src/themes/falu.ts

adding prop brandTitle to cobalt to make it cleaner when using custom fonts by relying on the theme
config
2963

feat(cobalt theme): add prop brandTitle to cobalt
